In [33]:
import pandas as pd
import numpy as np

In [34]:
df=pd.read_csv('news.csv')

In [35]:
df

,author,published,title,Unnamed: 3,Unnamed: 4,Unnamed: 5
0,Barracuda Brigade,2016-10-26T21:41:00.000+03:00,Muslims BUSTED: They Stole Millions In Gov’t B...,NaN,NaN,NaN
1,reasoning with facts,2016-10-29T08:47:11.259+03:00,Re: Why Did Attorney General Loretta Lynch Ple...,NaN,NaN,NaN
2,Barracuda Brigade,2016-10-31T01:41:49.479+02:00,BREAKING: Weiner Cooperating With FBI On Hilla...,NaN,NaN,NaN
3,Fed Up,2016-11-01T05:22:00.000+02:00,PIN DROP SPEECH BY FATHER OF DAUGHTER Kidnappe...,NaN,NaN,NaN
4,Fed Up,2016-11-01T21:56:00.000+02:00,FANTASTIC! TRUMP'S 7 POINT PLAN To Reform Heal...,NaN,NaN,NaN
...,...,...,...,...,...,...
12994,replaceme,2016-10-26T23:58:00.000+03:00,NaN,NaN,NaN,NaN
12995,Freedumb,2016-10-27T00:02:00.000+03:00,NaN,NaN,NaN,NaN
12996,major major maj...,2016-10-27T00:06:00.000+03:00,NaN,NaN,NaN,NaN
12997,beemasters,2016-10-27T00:09:00.000+03:00,NaN,NaN,NaN,NaN
12998,i&#039;m-confused,2016-10-27T00:09:00.000+03:00,NaN,NaN,NaN,NaN

In [36]:
df.shape

(12999, 6)

In [37]:
df.columns

Index(['author', 'published', 'title', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5'],
      dtype='object')

In [38]:
df.isnull().sum()

author         2424
published         0
title           680
Unnamed: 3    12999
Unnamed: 4    12999
Unnamed: 5    12999
dtype: int64

In [41]:
df.drop(columns='Unnamed: 5', axis=1, inplace=True)

In [42]:
df

,author,published,title
0,Barracuda Brigade,2016-10-26T21:41:00.000+03:00,Muslims BUSTED: They Stole Millions In Gov’t B...
1,reasoning with facts,2016-10-29T08:47:11.259+03:00,Re: Why Did Attorney General Loretta Lynch Ple...
2,Barracuda Brigade,2016-10-31T01:41:49.479+02:00,BREAKING: Weiner Cooperating With FBI On Hilla...
3,Fed Up,2016-11-01T05:22:00.000+02:00,PIN DROP SPEECH BY FATHER OF DAUGHTER Kidnappe...
4,Fed Up,2016-11-01T21:56:00.000+02:00,FANTASTIC! TRUMP'S 7 POINT PLAN To Reform Heal...
...,...,...,...
12994,replaceme,2016-10-26T23:58:00.000+03:00,NaN
12995,Freedumb,2016-10-27T00:02:00.000+03:00,NaN
12996,major major maj...,2016-10-27T00:06:00.000+03:00,NaN
12997,beemasters,2016-10-27T00:09:00.000+03:00,NaN
12998,i&#039;m-confused,2016-10-27T00:09:00.000+03:00,NaN

In [43]:
df.drop_duplicates(subset='author', keep=False, inplace=True)

In [44]:
df

,author,published,title
1,reasoning with facts,2016-10-29T08:47:11.259+03:00,Re: Why Did Attorney General Loretta Lynch Ple...
55,Branko Mali,2016-11-25T14:33:14.332+02:00,Hell Comes to Frogtown: Alt Right and Triumph ...
80,pak alresky,2016-10-28T11:58:00.000+03:00,NaN
119,IBU SUMIATUNG,2016-10-31T12:28:00.000+02:00,NaN
147,Steve smith,2016-11-01T22:22:00.000+02:00,NaN
...,...,...,...
12994,replaceme,2016-10-26T23:58:00.000+03:00,NaN
12995,Freedumb,2016-10-27T00:02:00.000+03:00,NaN
12996,major major maj...,2016-10-27T00:06:00.000+03:00,NaN
12997,beemasters,2016-10-27T00:09:00.000+03:00,NaN
12998,i&#039;m-confused,2016-10-27T00:09:00.000+03:00,NaN

In [48]:
df1=df.dropna()
df1

,author,published,title
1,reasoning with facts,2016-10-29T08:47:11.259+03:00,Re: Why Did Attorney General Loretta Lynch Ple...
55,Branko Mali,2016-11-25T14:33:14.332+02:00,Hell Comes to Frogtown: Alt Right and Triumph ...
160,Peeple,2016-10-27T00:53:00.000+03:00,We Know The Truth
162,seentoomuch,2016-10-26T21:13:00.000+03:00,Found this nugget in Podesta files Fastwalkers...
163,vlawde,2016-10-27T02:54:39.811+03:00,EMP event forthcoming?
...,...,...,...
12381,Jason Bermas,2016-11-06T20:25:29.050+02:00,The Sex Scandal That Could Change The Election
12509,Old_Logan,2016-11-09T20:06:00.000+02:00,National Attention On Ayotte - Hassan (*NH) Se...
12595,Conover Kennard,2016-11-12T07:00:00.000+02:00,Trumpians Mistake Lupus Patient’s Head Coverin...
12806,administrator,2016-10-27T13:29:57.926+03:00,WikiLeaks: Hillary Admits Clinton Foundation D...
12910,George Washington,2016-10-26T23:53:49.879+03:00,Fact Check: Trump Is Right that Clinton Might ...

In [50]:
df1.head()

,author,published,title
1,reasoning with facts,2016-10-29T08:47:11.259+03:00,Re: Why Did Attorney General Loretta Lynch Ple...
55,Branko Mali,2016-11-25T14:33:14.332+02:00,Hell Comes to Frogtown: Alt Right and Triumph ...
160,Peeple,2016-10-27T00:53:00.000+03:00,We Know The Truth
162,seentoomuch,2016-10-26T21:13:00.000+03:00,Found this nugget in Podesta files Fastwalkers...
163,vlawde,2016-10-27T02:54:39.811+03:00,EMP event forthcoming?

In [51]:
df1.tail()

,author,published,title
12381,Jason Bermas,2016-11-06T20:25:29.050+02:00,The Sex Scandal That Could Change The Election
12509,Old_Logan,2016-11-09T20:06:00.000+02:00,National Attention On Ayotte - Hassan (*NH) Se...
12595,Conover Kennard,2016-11-12T07:00:00.000+02:00,Trumpians Mistake Lupus Patient’s Head Coverin...
12806,administrator,2016-10-27T13:29:57.926+03:00,WikiLeaks: Hillary Admits Clinton Foundation D...
12910,George Washington,2016-10-26T23:53:49.879+03:00,Fact Check: Trump Is Right that Clinton Might ...

In [54]:
df1.describe()

,author,published,title
count,1043,1043,1043
unique,1043,975,1042
top,سعيد هلال الشريفي,2016-11-01T02:00:00.000+02:00,The Pathologization of Dissent
freq,1,9,2

In [56]:
df1.reindex()

,author,published,title
1,reasoning with facts,2016-10-29T08:47:11.259+03:00,Re: Why Did Attorney General Loretta Lynch Ple...
55,Branko Mali,2016-11-25T14:33:14.332+02:00,Hell Comes to Frogtown: Alt Right and Triumph ...
160,Peeple,2016-10-27T00:53:00.000+03:00,We Know The Truth
162,seentoomuch,2016-10-26T21:13:00.000+03:00,Found this nugget in Podesta files Fastwalkers...
163,vlawde,2016-10-27T02:54:39.811+03:00,EMP event forthcoming?
...,...,...,...
12381,Jason Bermas,2016-11-06T20:25:29.050+02:00,The Sex Scandal That Could Change The Election
12509,Old_Logan,2016-11-09T20:06:00.000+02:00,National Attention On Ayotte - Hassan (*NH) Se...
12595,Conover Kennard,2016-11-12T07:00:00.000+02:00,Trumpians Mistake Lupus Patient’s Head Coverin...
12806,administrator,2016-10-27T13:29:57.926+03:00,WikiLeaks: Hillary Admits Clinton Foundation D...
12910,George Washington,2016-10-26T23:53:49.879+03:00,Fact Check: Trump Is Right that Clinton Might ...

In [62]:
df1.reset_index(inplace=True)

ValueError: cannot insert level_0, already exists

In [63]:
df1

,level_0,index,author,published,title
0,0,1,reasoning with facts,2016-10-29T08:47:11.259+03:00,Re: Why Did Attorney General Loretta Lynch Ple...
1,1,55,Branko Mali,2016-11-25T14:33:14.332+02:00,Hell Comes to Frogtown: Alt Right and Triumph ...
2,2,160,Peeple,2016-10-27T00:53:00.000+03:00,We Know The Truth
3,3,162,seentoomuch,2016-10-26T21:13:00.000+03:00,Found this nugget in Podesta files Fastwalkers...
4,4,163,vlawde,2016-10-27T02:54:39.811+03:00,EMP event forthcoming?
...,...,...,...,...,...
1038,1038,12381,Jason Bermas,2016-11-06T20:25:29.050+02:00,The Sex Scandal That Could Change The Election
1039,1039,12509,Old_Logan,2016-11-09T20:06:00.000+02:00,National Attention On Ayotte - Hassan (*NH) Se...
1040,1040,12595,Conover Kennard,2016-11-12T07:00:00.000+02:00,Trumpians Mistake Lupus Patient’s Head Coverin...
1041,1041,12806,administrator,2016-10-27T13:29:57.926+03:00,WikiLeaks: Hillary Admits Clinton Foundation D...
1042,1042,12910,George Washington,2016-10-26T23:53:49.879+03:00,Fact Check: Trump Is Right that Clinton Might ...

In [65]:
df1.set_index('level_0',inplace=True)

In [67]:
df1

,author,published,title
level_0,,,
0,reasoning with facts,2016-10-29T08:47:11.259+03:00,Re: Why Did Attorney General Loretta Lynch Ple...
1,Branko Mali,2016-11-25T14:33:14.332+02:00,Hell Comes to Frogtown: Alt Right and Triumph ...
2,Peeple,2016-10-27T00:53:00.000+03:00,We Know The Truth
3,seentoomuch,2016-10-26T21:13:00.000+03:00,Found this nugget in Podesta files Fastwalkers...
4,vlawde,2016-10-27T02:54:39.811+03:00,EMP event forthcoming?
...,...,...,...
1038,Jason Bermas,2016-11-06T20:25:29.050+02:00,The Sex Scandal That Could Change The Election
1039,Old_Logan,2016-11-09T20:06:00.000+02:00,National Attention On Ayotte - Hassan (*NH) Se...
1040,Conover Kennard,2016-11-12T07:00:00.000+02:00,Trumpians Mistake Lupus Patient’s Head Coverin...
1041,administrator,2016-10-27T13:29:57.926+03:00,WikiLeaks: Hillary Admits Clinton Foundation D...
1042,George Washington,2016-10-26T23:53:49.879+03:00,Fact Check: Trump Is Right that Clinton Might ...

In [70]:
df1.rename(columns={'level_0': 'Id'})

,author,published,title
level_0,,,
0,reasoning with facts,2016-10-29T08:47:11.259+03:00,Re: Why Did Attorney General Loretta Lynch Ple...
1,Branko Mali,2016-11-25T14:33:14.332+02:00,Hell Comes to Frogtown: Alt Right and Triumph ...
2,Peeple,2016-10-27T00:53:00.000+03:00,We Know The Truth
3,seentoomuch,2016-10-26T21:13:00.000+03:00,Found this nugget in Podesta files Fastwalkers...
4,vlawde,2016-10-27T02:54:39.811+03:00,EMP event forthcoming?
...,...,...,...
1038,Jason Bermas,2016-11-06T20:25:29.050+02:00,The Sex Scandal That Could Change The Election
1039,Old_Logan,2016-11-09T20:06:00.000+02:00,National Attention On Ayotte - Hassan (*NH) Se...
1040,Conover Kennard,2016-11-12T07:00:00.000+02:00,Trumpians Mistake Lupus Patient’s Head Coverin...
1041,administrator,2016-10-27T13:29:57.926+03:00,WikiLeaks: Hillary Admits Clinton Foundation D...
1042,George Washington,2016-10-26T23:53:49.879+03:00,Fact Check: Trump Is Right that Clinton Might ...

In [72]:
df=df1

In [73]:
df

,author,published,title
level_0,,,
0,reasoning with facts,2016-10-29T08:47:11.259+03:00,Re: Why Did Attorney General Loretta Lynch Ple...
1,Branko Mali,2016-11-25T14:33:14.332+02:00,Hell Comes to Frogtown: Alt Right and Triumph ...
2,Peeple,2016-10-27T00:53:00.000+03:00,We Know The Truth
3,seentoomuch,2016-10-26T21:13:00.000+03:00,Found this nugget in Podesta files Fastwalkers...
4,vlawde,2016-10-27T02:54:39.811+03:00,EMP event forthcoming?
...,...,...,...
1038,Jason Bermas,2016-11-06T20:25:29.050+02:00,The Sex Scandal That Could Change The Election
1039,Old_Logan,2016-11-09T20:06:00.000+02:00,National Attention On Ayotte - Hassan (*NH) Se...
1040,Conover Kennard,2016-11-12T07:00:00.000+02:00,Trumpians Mistake Lupus Patient’s Head Coverin...
1041,administrator,2016-10-27T13:29:57.926+03:00,WikiLeaks: Hillary Admits Clinton Foundation D...
1042,George Washington,2016-10-26T23:53:49.879+03:00,Fact Check: Trump Is Right that Clinton Might ...

In [74]:
df.isnull().sum()

author       0
published    0
title        0
dtype: int64

In [76]:
type(df)

pandas.core.frame.DataFrame

In [77]:
import nltk
import os
from nltk.tokenize import word_tokenize